---
- name: Install and Configure an IIS site 
  hosts: winserver
  gather_facts: true

  vars:

  tasks:
    - name: print hello world
      debug:
        msg: 'hello world'
    
    - name: IIS and .Net 4.5 are installed
      ansible.windows.win_feature:
        name: 
          - web-server
          - NET-Framework-Core
          - Web-Asp-Net45
        include_management_tools: true
        state: present
        
    - name: Logs Directory is created
      win_file:
        path: C:\sites\logs
        state: Directory

    - name: Site Directory is created
      win_copy:
        path: C:\sites\variables
        state: directory

    - name: HTML page for the site
      win_copy:
        src: C:\temp
        dest: c:\sites\variables
        remote_src: yes






  
