---
- name: Install and Configure an IIS site 
  hosts: winserver
  gather_facts: true

  vars:

  tasks:
    - name: print hello world
      debug:
        msg: 'hello world'
    
    - name: IIS and .Net 4.5 are installed
      ansible.windows.win_feature:
        name: 
          - web-server
          - NET-Framework-Core
          - Web-Asp-Net45
        state: present
        include_management_tools: true
        




  
