---
- name: Install and Configure httpd
  hosts: linux001
  become: yes
  tasks:
     - name: install httpd and firewalld
       yum:
          - httpd
          - firewalld
       state: present


 



