---
- name: Install and Configure Windows package
  hosts: winserver
  gather_facts: true

  vars:

  tasks:
    - name: Install Windows package
      win_package:
        path: https://get.videolan.org/vlc/3.0.7.1/win64/vlc-3.0.7.1-win64.exe
        product_id: 'VLC media player'
        state: present
        arguments: /S 
      register: install_result

    - name: Install TFTP server
      win_package: 
        path: https://cdn.winscp.net/files/WinSCP-5.19.6-Setup.exe?secure=9LRs1csLUv7e2Gwar_SUyg==,1647025617
        product_id: 'TFTP server for Windows'
        state: present
        arguments: /S 
      register: install_result

    - debug:
        var: install_result



       



