---
- hosts: linux001,linux002
  become: true
  gather_facts: all
  
  tasks:
  - name: Install Apache 
    yum: 
       name: httpd
       state: latest
    when: ansible_distribution in  ["RedHat"]

  - name: Check for the package
    yum:
       name: httpd
       state: present
    when: ansible_distribution in  ["RedHat"]

  - name: Upgrade all packages
    yum:
       name: '*' 
       state: latest
    when: ansible_distribution in  ["RedHat"]

  - name: List Ansible packages
    yum:
       list: ansible
    register: result
    when: ansible_distribution in  ["RedHat"]
    #new comment




      



