---
- name: Install and Configure HTTPD and FIREWALLD
  hosts: linux001
  become: yes

  vars:
  vars_files:
   - vars/vars.yml

  tasks:
   -  name: Install and configure httpd and FIREWALLD
      yum:
        name:
          - "{{ web_package }}"
          -  "{{ firewall_package }}"
        state: latest

   -  name: Enable and Start httpd
      service:
        name: "{{ web_service }}"
        state: started

   -  name: Start FirewallD service
      service:
        name: "{{ firewall_service }}"
        state: started


          





      




