---
- name: Install and Configure an IIS site 
  hosts: winserver
  gather_facts: true

  vars:

  tasks:
    - name: print hello world
      debug:
        msg: 'hello world'
    
    - name: IIS and .Net 4.5 are installed
      ansible.windows.win_feature:
        name: web_server
        state: present

        


  
