---
- hosts: linux001,linux002
  become: true
  gather_facts: true
  tasks:
  - name: Install Apache 
    yum: 
       name: httpd
       state: latest

  - name: Check for the package
    yum:
       name: httpd
       state: present

  - name: Upgrade all packages
    yum:
       name: '*' 
       state: latest

  - name: List Ansible packages
    yum:
       list: ansible
    register: result


      



