---
- name: This is an Example of Windows Copy File 
  hosts:  winserver
  gather_facts: true

  tasks:
    - name: Copy a Windows File
      win_copy:
        src: c:\readme.txt
        dest: c:\temp\
        remote_src: yes


