---
- name: Example for Windows Copy
  hosts: winansible
  become: false
  gather_facts: yes

  vars: 
   source: "/tmp/foo.txt"
   destination: C:\Temp\foo.txt

  tasks:
    - name: Copy a single file
      ansible.windows.win_copy:
        src: "{{ source }}"  
        dest: "{{ destination }}"


